# Generated by Django 3.2.7 on 2021-09-28 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_sis.models
import simple_sis.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', simple_sis.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('distance_from_school', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('NSW', 'Nsw'), ('QLD', 'Qld'), ('SA', 'Sa'), ('TAS', 'Tas'), ('VIC', 'Vic'), ('WA', 'Wa'), ('ACT', 'Act'), ('NT', 'Nt')], max_length=3)),
                ('postcode', models.CharField(max_length=4, validators=[simple_sis.validators.validate_postcode])),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simple_sis.location')),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccountType',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simple_sis.location')),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupCodeType',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LookupCode',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookup_codes', to='simple_sis.lookupcodetype')),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendee',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object created.')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this object updated.')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('attended_at', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simple_sis.activity')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simple_sis.lookupcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simple_sis.lookupcode'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='simple_sis.location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_by',
            field=models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='simple_sis.useraccounttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='simple_sis.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(help_text='Who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
