# Generated by Django 3.2.7 on 2021-09-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupcodetype',
            name='name',
        ),
    ]
