# Generated by Django 3.2.7 on 2021-09-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sis', '0004_rename_address_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='simple_sis.school'),
            preserve_default=False,
        ),
    ]
