# Generated by Django 3.2.7 on 2021-09-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sis', '0005_activity_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='simple_sis.venue'),
            preserve_default=False,
        ),
    ]
