# Generated by Django 3.2.7 on 2021-09-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sis', '0006_auto_20210928_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattendee',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='simple_sis.activity'),
        ),
    ]
